AWSTemplateFormatVersion: 2010-09-09
Description: |
  CludFormation Template to deploy Kittens Static WEbsite using S3, CloudFront, ACM, and Route 53
Parameters:
  DomainName:
    Type: AWS::Route53::HostedZone::Id
    Description: Domain Name hosted on Route53 
  KittensDomainName:
    Type: String
    Description: Subdomain ex kittens.clarusway.us
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Resources:
  KittensBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref KittensDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - "s3:GetObject"
            Effect: Allow
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref KittensBucket
                - /*
            Principal: "*"
  KittensCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED 
      DomainName: !Ref KittensDomainName # Required
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName 
      ValidationMethod: DNS 
  KittensDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DomainName 
      RecordSets:
        - AliasTarget:
            DNSName: !GetAtt KittensCloudFront.DomainName
            EvaluateTargetHealth: true
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Ref KittensDomainName 
          Type: A
  KittensCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref KittensDomainName
        Comment: CloudFront Distribution for Kittens Carousel Website
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true 
          ForwardedValues:
            Cookies:
              Forward: none 
            QueryString: true 
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true 
        HttpVersion: http2
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Select [2, !Split  ["/", !GetAtt KittensBucket.WebsiteURL]]
            Id: KittensOrigin
        ViewerCertificate:
          AcmCertificateArn: !Ref KittensCertificate
          SslSupportMethod: sni-only

Outputs:
  BucketName:
    Description: S3 Bucket Endpoint for Kittens Website
    Value: !GetAtt KittensBucket.WebsiteURL
  FullDomainName:
    Description: FQDN For Kittens Website
    Value: !Ref KittensDomainName
  DistroDN:
    Description: Cloudfront DN For Kittens Website 
    Value: !GetAtt KittensCloudFront.DomainName
  